version: "3"
services:
  client:
    build: ./shop
    image: client:latest 
    container_name: shop-client
    ports:
      - 8080:3000
    volumes:
      - ./shop:/usr/src/app
    depends_on:
      - api
    links:
      - api

  api:
    build: ./shop-api
    ports:
      - 3000:3000
    container_name: 'shop-api'
    volumes:
      - ./shop-api:/home/node/app
    depends_on:
      - db
    links:
      - db

  db:
    image: mongo:latest
    container_name: shop-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: shopdb
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: adminpassw0rd